model: weights/yolov8s-world.pt
data: configs/visdrone_yolo_prepared.yaml
project: runs/visdrone_yoloworld
name: visdrone_v1
epochs: 50
imgsz: 960
batch: 8
device: 0
workers: 8
seed: 42
patience: 15
optimizer: auto
lr0: 0.001
cos_lr: true
rect: true
amp: true
cache: false
plots: true
exist_ok: true
verbose: true
close_mosaic: 10